// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: ProtoInner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InnerHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromServerUid    int64 `protobuf:"varint,1,opt,name=fromServerUid,proto3" json:"fromServerUid,omitempty"`
	ToServerUid      int64 `protobuf:"varint,2,opt,name=toServerUid,proto3" json:"toServerUid,omitempty"`
	ReceiveServerUid int64 `protobuf:"varint,3,opt,name=receiveServerUid,proto3" json:"receiveServerUid,omitempty"`
	Id               int64 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	SendType         int32 `protobuf:"varint,5,opt,name=sendType,proto3" json:"sendType,omitempty"`
	ProtoCode        int32 `protobuf:"varint,6,opt,name=protoCode,proto3" json:"protoCode,omitempty"`
	CallbackId       int64 `protobuf:"varint,7,opt,name=callbackId,proto3" json:"callbackId,omitempty"`
}

func (x *InnerHead) Reset() {
	*x = InnerHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProtoInner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerHead) ProtoMessage() {}

func (x *InnerHead) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoInner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerHead.ProtoReflect.Descriptor instead.
func (*InnerHead) Descriptor() ([]byte, []int) {
	return file_ProtoInner_proto_rawDescGZIP(), []int{0}
}

func (x *InnerHead) GetFromServerUid() int64 {
	if x != nil {
		return x.FromServerUid
	}
	return 0
}

func (x *InnerHead) GetToServerUid() int64 {
	if x != nil {
		return x.ToServerUid
	}
	return 0
}

func (x *InnerHead) GetReceiveServerUid() int64 {
	if x != nil {
		return x.ReceiveServerUid
	}
	return 0
}

func (x *InnerHead) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InnerHead) GetSendType() int32 {
	if x != nil {
		return x.SendType
	}
	return 0
}

func (x *InnerHead) GetProtoCode() int32 {
	if x != nil {
		return x.ProtoCode
	}
	return 0
}

func (x *InnerHead) GetCallbackId() int64 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

type InnerLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId int64 `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	AccountId int64 `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	RoleId    int64 `protobuf:"varint,3,opt,name=roleId,proto3" json:"roleId,omitempty"`
}

func (x *InnerLoginRequest) Reset() {
	*x = InnerLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProtoInner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerLoginRequest) ProtoMessage() {}

func (x *InnerLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoInner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerLoginRequest.ProtoReflect.Descriptor instead.
func (*InnerLoginRequest) Descriptor() ([]byte, []int) {
	return file_ProtoInner_proto_rawDescGZIP(), []int{1}
}

func (x *InnerLoginRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *InnerLoginRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *InnerLoginRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type InnerLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId int64 `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
}

func (x *InnerLoginResponse) Reset() {
	*x = InnerLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProtoInner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerLoginResponse) ProtoMessage() {}

func (x *InnerLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoInner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerLoginResponse.ProtoReflect.Descriptor instead.
func (*InnerLoginResponse) Descriptor() ([]byte, []int) {
	return file_ProtoInner_proto_rawDescGZIP(), []int{2}
}

func (x *InnerLoginResponse) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type InnerBuildingLevelUpSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildingId int64 `protobuf:"varint,1,opt,name=buildingId,proto3" json:"buildingId,omitempty"`
	ConfigId   int32 `protobuf:"varint,2,opt,name=configId,proto3" json:"configId,omitempty"`
}

func (x *InnerBuildingLevelUpSuccess) Reset() {
	*x = InnerBuildingLevelUpSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProtoInner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerBuildingLevelUpSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerBuildingLevelUpSuccess) ProtoMessage() {}

func (x *InnerBuildingLevelUpSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoInner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerBuildingLevelUpSuccess.ProtoReflect.Descriptor instead.
func (*InnerBuildingLevelUpSuccess) Descriptor() ([]byte, []int) {
	return file_ProtoInner_proto_rawDescGZIP(), []int{3}
}

func (x *InnerBuildingLevelUpSuccess) GetBuildingId() int64 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

func (x *InnerBuildingLevelUpSuccess) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

type InnerLoginNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId           int64  `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	GameServerUid    int64  `protobuf:"varint,2,opt,name=gameServerUid,proto3" json:"gameServerUid,omitempty"`
	GatewayServerUid int64  `protobuf:"varint,3,opt,name=gatewayServerUid,proto3" json:"gatewayServerUid,omitempty"`
	WorldUnitId      int64  `protobuf:"varint,4,opt,name=worldUnitId,proto3" json:"worldUnitId,omitempty"`
	Name             string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	WorldPositionX   int32  `protobuf:"varint,6,opt,name=worldPositionX,proto3" json:"worldPositionX,omitempty"`
	WorldPositionZ   int32  `protobuf:"varint,7,opt,name=worldPositionZ,proto3" json:"worldPositionZ,omitempty"`
}

func (x *InnerLoginNotify) Reset() {
	*x = InnerLoginNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProtoInner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerLoginNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerLoginNotify) ProtoMessage() {}

func (x *InnerLoginNotify) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoInner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerLoginNotify.ProtoReflect.Descriptor instead.
func (*InnerLoginNotify) Descriptor() ([]byte, []int) {
	return file_ProtoInner_proto_rawDescGZIP(), []int{4}
}

func (x *InnerLoginNotify) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *InnerLoginNotify) GetGameServerUid() int64 {
	if x != nil {
		return x.GameServerUid
	}
	return 0
}

func (x *InnerLoginNotify) GetGatewayServerUid() int64 {
	if x != nil {
		return x.GatewayServerUid
	}
	return 0
}

func (x *InnerLoginNotify) GetWorldUnitId() int64 {
	if x != nil {
		return x.WorldUnitId
	}
	return 0
}

func (x *InnerLoginNotify) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InnerLoginNotify) GetWorldPositionX() int32 {
	if x != nil {
		return x.WorldPositionX
	}
	return 0
}

func (x *InnerLoginNotify) GetWorldPositionZ() int32 {
	if x != nil {
		return x.WorldPositionZ
	}
	return 0
}

type InnerLogoutNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId int64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
}

func (x *InnerLogoutNotify) Reset() {
	*x = InnerLogoutNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProtoInner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerLogoutNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerLogoutNotify) ProtoMessage() {}

func (x *InnerLogoutNotify) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoInner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerLogoutNotify.ProtoReflect.Descriptor instead.
func (*InnerLogoutNotify) Descriptor() ([]byte, []int) {
	return file_ProtoInner_proto_rawDescGZIP(), []int{5}
}

func (x *InnerLogoutNotify) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type InnerLoginInitNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId int64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
}

func (x *InnerLoginInitNotify) Reset() {
	*x = InnerLoginInitNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProtoInner_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerLoginInitNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerLoginInitNotify) ProtoMessage() {}

func (x *InnerLoginInitNotify) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoInner_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerLoginInitNotify.ProtoReflect.Descriptor instead.
func (*InnerLoginInitNotify) Descriptor() ([]byte, []int) {
	return file_ProtoInner_proto_rawDescGZIP(), []int{6}
}

func (x *InnerLoginInitNotify) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type InnerReikiStatement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element    int32 `protobuf:"varint,1,opt,name=element,proto3" json:"element,omitempty"`
	Level      int32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	SeriousNum int64 `protobuf:"varint,3,opt,name=seriousNum,proto3" json:"seriousNum,omitempty"` //重伤数 进医院
	DeadNum    int64 `protobuf:"varint,4,opt,name=deadNum,proto3" json:"deadNum,omitempty"`       //死亡数 直接扣除
}

func (x *InnerReikiStatement) Reset() {
	*x = InnerReikiStatement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProtoInner_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerReikiStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerReikiStatement) ProtoMessage() {}

func (x *InnerReikiStatement) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoInner_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerReikiStatement.ProtoReflect.Descriptor instead.
func (*InnerReikiStatement) Descriptor() ([]byte, []int) {
	return file_ProtoInner_proto_rawDescGZIP(), []int{7}
}

func (x *InnerReikiStatement) GetElement() int32 {
	if x != nil {
		return x.Element
	}
	return 0
}

func (x *InnerReikiStatement) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *InnerReikiStatement) GetSeriousNum() int64 {
	if x != nil {
		return x.SeriousNum
	}
	return 0
}

func (x *InnerReikiStatement) GetDeadNum() int64 {
	if x != nil {
		return x.DeadNum
	}
	return 0
}

// 战斗重伤死亡灵气结算 通知game扣除死亡灵气、重伤灵气进医院
type InnerBattleReikiStatementNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReikiStatements []*InnerReikiStatement `protobuf:"bytes,1,rep,name=reikiStatements,proto3" json:"reikiStatements,omitempty"`
}

func (x *InnerBattleReikiStatementNotify) Reset() {
	*x = InnerBattleReikiStatementNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProtoInner_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerBattleReikiStatementNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerBattleReikiStatementNotify) ProtoMessage() {}

func (x *InnerBattleReikiStatementNotify) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoInner_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerBattleReikiStatementNotify.ProtoReflect.Descriptor instead.
func (*InnerBattleReikiStatementNotify) Descriptor() ([]byte, []int) {
	return file_ProtoInner_proto_rawDescGZIP(), []int{8}
}

func (x *InnerBattleReikiStatementNotify) GetReikiStatements() []*InnerReikiStatement {
	if x != nil {
		return x.ReikiStatements
	}
	return nil
}

var File_ProtoInner_proto protoreflect.FileDescriptor

var file_ProtoInner_proto_rawDesc = []byte{
	0x0a, 0x10, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xe9, 0x01, 0x0a, 0x09,
	0x49, 0x6e, 0x6e, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x72, 0x6f,
	0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x69, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x69,
	0x64, 0x12, 0x2a, 0x0a, 0x10, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x55, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x69, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x11, 0x49, 0x6e, 0x6e, 0x65, 0x72,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x22, 0x2c, 0x0a, 0x12, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x59,
	0x0a, 0x1b, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x22, 0x82, 0x02, 0x0a, 0x10, 0x49, 0x6e,
	0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x67,
	0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x10,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x55, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x26, 0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x22, 0x2b,
	0x0a, 0x11, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x14, 0x49,
	0x6e, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x7f, 0x0a, 0x13, 0x49,
	0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x69, 0x6b, 0x69, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x69, 0x6f, 0x75, 0x73, 0x4e, 0x75, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x69, 0x6f, 0x75, 0x73, 0x4e,
	0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x61, 0x64, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x65, 0x61, 0x64, 0x4e, 0x75, 0x6d, 0x22, 0x69, 0x0a, 0x1f,
	0x49, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x69, 0x6b, 0x69,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x46, 0x0a, 0x0f, 0x72, 0x65, 0x69, 0x6b, 0x69, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x69, 0x6b, 0x69, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0f, 0x72, 0x65, 0x69, 0x6b, 0x69, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x18, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ProtoInner_proto_rawDescOnce sync.Once
	file_ProtoInner_proto_rawDescData = file_ProtoInner_proto_rawDesc
)

func file_ProtoInner_proto_rawDescGZIP() []byte {
	file_ProtoInner_proto_rawDescOnce.Do(func() {
		file_ProtoInner_proto_rawDescData = protoimpl.X.CompressGZIP(file_ProtoInner_proto_rawDescData)
	})
	return file_ProtoInner_proto_rawDescData
}

var file_ProtoInner_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ProtoInner_proto_goTypes = []interface{}{
	(*InnerHead)(nil),                       // 0: message.InnerHead
	(*InnerLoginRequest)(nil),               // 1: message.InnerLoginRequest
	(*InnerLoginResponse)(nil),              // 2: message.InnerLoginResponse
	(*InnerBuildingLevelUpSuccess)(nil),     // 3: message.InnerBuildingLevelUpSuccess
	(*InnerLoginNotify)(nil),                // 4: message.InnerLoginNotify
	(*InnerLogoutNotify)(nil),               // 5: message.InnerLogoutNotify
	(*InnerLoginInitNotify)(nil),            // 6: message.InnerLoginInitNotify
	(*InnerReikiStatement)(nil),             // 7: message.InnerReikiStatement
	(*InnerBattleReikiStatementNotify)(nil), // 8: message.InnerBattleReikiStatementNotify
}
var file_ProtoInner_proto_depIdxs = []int32{
	7, // 0: message.InnerBattleReikiStatementNotify.reikiStatements:type_name -> message.InnerReikiStatement
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ProtoInner_proto_init() }
func file_ProtoInner_proto_init() {
	if File_ProtoInner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ProtoInner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProtoInner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProtoInner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProtoInner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerBuildingLevelUpSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProtoInner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerLoginNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProtoInner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerLogoutNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProtoInner_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerLoginInitNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProtoInner_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerReikiStatement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ProtoInner_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerBattleReikiStatementNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ProtoInner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ProtoInner_proto_goTypes,
		DependencyIndexes: file_ProtoInner_proto_depIdxs,
		MessageInfos:      file_ProtoInner_proto_msgTypes,
	}.Build()
	File_ProtoInner_proto = out.File
	file_ProtoInner_proto_rawDesc = nil
	file_ProtoInner_proto_goTypes = nil
	file_ProtoInner_proto_depIdxs = nil
}
