package constants

const (
	INNER_MSG_SEND_AUTO           = 0
	INNER_MSG_SEND_FORWARD        = 1
	INNER_MSG_SEND_CALLBACK       = 2
	INNER_MSG_SEND_CALLBACK_REPLY = 3
	INNER_MSG_SEND_CLIENT         = 8
)
